---
- name: Remove insecure packages
  ansible.builtin.apt:
    name: "{{ hardening_insecure_packages }}"
    state: absent
    purge: true
  when: hardening_remove_insecure_packages | bool

- name: Ensure required hardening packages are installed
  ansible.builtin.package:
    name: "{{ hardening_required_packages }}"
    state: present
  when: hardening_manage_packages | bool
