---
- name: Ensure sudo logfile exists
  ansible.builtin.file:
    path: "{{ hardening_sudo_logfile }}"
    state: touch
    owner: root
    group: root
    mode: "0600"
    modification_time: preserve
    access_time: preserve

- name: Deploy sudo policy drop-in
  ansible.builtin.copy:
    dest: /etc/sudoers.d/50-hardening
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
    content: |
      Defaults logfile="{{ hardening_sudo_logfile }}"
      {% if hardening_sudo_require_reauthentication %}
      Defaults timestamp_timeout=0
      {% endif %}
